blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [

    path('index/', views.index),
    path('article/<int:article_id>/', views.article_page,name='article_page'),
    # 使用django2.0提供的path转换器，直接使用‘<>’捕获值，例如<int:article_id>，需指定类型
    path('edit/<int:article_id>/', views.edit_page,name='edit_page'),
    path('edit/action/', views.edit_action,name='edit_action'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
]

blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model): # 修改记得在cmd里移植（migration+migrate）
    title=models.CharField(max_length=32,default='Title')
    content=models.TextField(null=True)
    pub_time=models.DateTimeField(null=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from . import models
def index(request):
    # return HttpResponse("Hello world!")
    article=models.Article.objects.all() # all返回查询集合（列表）
    return render(request, 'blog/index.html', {'article': article})

def article_page(request,article_id):
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})

def edit_page(request,article_id):
    if str(article_id) == '0':
        return render(request,'blog/edit_page.html')
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/edit_page.html',{'article':article})

def edit_action(request):
    title=request.POST.get('title','TITLE')
    content=request.POST.get('content','CONTENT')
    article_id=request.POST.get('article_id','0')
    if str(article_id )== "0" :
        models.Article.objects.create(title=title,content=content)
        article = models.Article.objects.all()  # all返回查询集合（列表）
        return render(request, 'blog/index.html', {'article': article})
    article=models.Article.objects.get(pk=article_id)
    article.title=title
    article.content=content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <br/>
    <h3>{{ article.content }}</h3>
    <br/><br/>
    <a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %} <!--网站安全性问题 -->
        <!--过滤器设置默认0；如果新建文章，则会出现未知变量article，Django不会报错，默认为空值 -->
        <input type="hidden" name="article_id" value="{{ article.id |default:'0'}}"/>
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <br/>
        <input type="submit" value="提交">

    </form>
</body>
</html>

blog/templates/blog/edit_page_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %} <!--网站安全性问题 -->

        {% if article %}
            <input type="hidden" name="article_id" value="{{ article.id }}"/>
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <br/>
        <input type="submit" value="提交">
        {% else %}
            <input type="hidden" name="article_id" value="0"/>
        <label>文章标题
            <input type="text" name="title">
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content">
        </label>
        <br/>
        <input type="submit" value="提交">
        {% endif %}
    </form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
{% for article in article %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}

</body>
</html>